#!/bin/bash

usage()
{
cat << EOF

==========================================================
Morevna Studio - software manager for animation production
==========================================================

Usage:
    morevna-studio-open file [APP [ARGS]]
   
Examples:
    morevna-studio-open /home/user/file.blend
    morevna-studio-open /home/user/file.blend blender

EOF
}

main()
{

    if [ -z "$1" ]; then
	usage
	exit 1
    fi
    
    if [ -z "$1" ]; then
	usage
	exit 1
    fi
    
    #TODO: Implement application chooser
    if [ -z "$2" ]; then
	usage
	exit 1
    fi
    
    APP=$2
    
    SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    cd `dirname "$1"`
    ${SCRIPTPATH}/morevna-studio exec "${APP}" "$1" "${@:3}"
    
}

main "$@"
