#!/bin/bash

MOREVNASTUDIO_VERSION=0.1

set -e

exec()
{
    # TODO: Update if needed
    # if MOREVNASTUDIO_VERSION ...
    
    MOREVNASTUDIO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    
    source "${MOREVNASTUDIO_DIR}/apps/${1}.conf"
    
    APP_NAME_UPPERCASE=`printf '%s\n' "$1" | awk '{ print toupper($0) }'`
    
    #APP_VERSION=$MOREVNA_VERSION_BLENDER
    eval APP_VERSION='$MOREVNA_VERSION_'$APP_NAME_UPPERCASE
    
    if [ -z $APP_VERSION ]; then
	# TODO: Detect version from RenderChan
	echo ...
    fi
    
    VERSION_OPTION=""
    if [ ! -z $APP_VERSION ]; then
	VERSION_OPTION="--version=${APP_VERSION}"
    fi
    
    0install run ${VERSION_OPTION} ${URI} "${@:2}"
}

install()
{
    echo "Installing Morevna Studio..."
    
    # TODO: install scripts from "launchers/" dir
    
    # TODO: ask location for packages (allow to place on SSD partition)
}

uninstall()
{
    echo "Uninstalling Morevna Studio..."
    # TODO: revert all operations done by install action
}

usage()
{
cat << EOF

==========================================================
Morevna Studio - software manager for animation production
==========================================================

Usage:
    morevna-studio exec APP [ARGS]
    morevna-studio install
    morevna-studio uninstall
   
Examples:
    morevna-studio exec blender
    morevna-studio exec blender --help
    MOREVNA_VERSION_BLENDER=2.78-1 morevna-studio exec blender

EOF
}

main()
{
    # TODO: Check if 0install available
    # ...
    
    if [ -z "$1" ]; then
	usage
	exit 1
    fi
    
    case $1 in
	exec)
	    if [ -z "$2" ]; then
		usage
		exit 1
	    fi
	    exec "${@:2}"
	    ;;
	install)      
	    install
	    ;;
	uninstall)
	    uninstall
	    ;;
	*)
	    usage
	    ;;
esac
}

main "$@"
