#!/bin/bash

MOREVNASTUDIO_VERSION=0.1

set -e

find_version() {
	if [ -d "$1" ]; then
		pushd "$1" >/dev/null
		TESTDIR=`pwd -P`
		popd >/dev/null
	else
		TESTDIR="$1"
	fi
	if [ -f "$TESTDIR/packages.txt" ]; then
		# Read contents of file
		VERSION=""
		while IFS= read -r line
		do
		    PACKAGE="${line%%=*}"
		    if [[ "$PACKAGE" == "$APP" ]]; then
			VERSION="${line#*=}"
			break
		    fi
		done < "$TESTDIR/packages.txt"
		if [ -z "$VERSION" ]; then
		    find_version "`dirname \"$TESTDIR\"`"
		else
		    echo "$VERSION"
		fi
	else
		if [[ "$TESTDIR" == '/' ]]; then
			exit
		fi
		find_version "`dirname \"$TESTDIR\"`"
	fi
}

exec()
{
    
    if [ -z ${MOREVNASTUDIO_PATH_IS_SET} ];then
    export PATH="${MOREVNASTUDIO_DIR}/bin/:$PATH"
    fi
    export MOREVNASTUDIO_PATH_IS_SET=1

    source ${MOREVNASTUDIO_DIR}/etc/morevna-studio.conf
    
    if [ -f $HOME/.config/morevna-studio/morevna-studio.conf ]; then
    source $HOME/.config/morevna-studio/morevna-studio.conf
    fi
    if [ ! -z $MOREVNASTUDIO_CACHEDIR ]; then
    export ZEROINSTALL_PORTABLE_BASE=$MOREVNASTUDIO_CACHEDIR
    fi
    
    if [ -f $HOME/.config/morevna-studio/morevna-studio.version ]; then
	source $HOME/.config/morevna-studio/morevna-studio.version
    fi
    if [ "x$MOREVNASTUDIO_VERSION" != "x$MOREVNASTUDIO_INSTALLED_VERSION" ]; then
	if [ -f "${MOREVNASTUDIO_DIR}/lib/morevna-studio/user-install" ]; then
	    bash "${MOREVNASTUDIO_DIR}/lib/morevna-studio/user-install"
	fi
    fi
    
    export APP="$1"
    
    source "${MOREVNASTUDIO_DIR}/share/morevna-studio/packages/${APP}.conf"
    
    #APP_NAME_UPPERCASE=`printf '%s\n' "$1" | awk '{ print toupper($0) }'`
    #
    #APP_VERSION=$MOREVNA_VERSION_BLENDER
    #eval APP_VERSION='$MOREVNA_VERSION_'$APP_NAME_UPPERCASE
    #
    #if [ -z $APP_VERSION ]; then
	# TODO: Detect version from RenderChan
	#echo ...
    #fi
    
    # find which file we are working with
    ARG_FILE=""
    for ARG in "$@"; do
	for EXT in "${EXTENSIONS[@]}"; do
	    if [[ "$ARG" == *.${EXT} ]]; then
		ARG_FILE="${ARG}"
	    fi
	done
    done
    
    # find package version defined for this file
    if [ ! -z "${ARG_FILE}" ]; then
	APP_VERSION=$(find_version `dirname "${ARG_FILE}"`)
    else
	APP_VERSION=$(find_version `pwd`)
    fi
    
    # 1. Look for installed package in opt
    # 1.a. If version is empty
    #  - ini configuration
    #  - /opt/package
    #  - 0install
    #  - /opt/package-version (latest) (fallback)
    # 1.b. If version is not empty
    #  - ini configuration
    #  - /opt/package-version
    #  - 0install
    
    VERSION_OPTION=""
    if [ ! -z $APP_VERSION ]; then
	VERSION_OPTION="--version=${APP_VERSION}"
    fi
    
    0install run ${VERSION_OPTION} ${URI_0INSTALL} "${@:2}"
}

usage()
{
cat << EOF

==========================================================
Morevna Studio - software manager for animation production
==========================================================

Usage:
    morevna-studio exec APP [ARGS]
   
Examples:
    morevna-studio exec blender
    morevna-studio exec blender --help
    MOREVNA_VERSION_BLENDER=2.78-1 morevna-studio exec blender

EOF
}

main()
{
    # TODO: Check if 0install available
    # ...
    
    if [ -z "$1" ]; then
	usage
	exit 1
    fi
    
    SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    export MOREVNASTUDIO_DIR=`dirname "$SCRIPTPATH"`
    MOREVNASTUDIO_DIR=`dirname "$MOREVNASTUDIO_DIR"`
    
    case $1 in
	exec)
	    if [ -z "$2" ]; then
		usage
		exit 1
	    fi
	    exec "${@:2}"
	    ;;
	*)
	    usage
	    ;;
esac
}

main "$@"
