#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export MOREVNASTUDIO_DIR=`dirname "$SCRIPTPATH"`
MOREVNASTUDIO_DIR=`dirname "$MOREVNASTUDIO_DIR"`

uninstall()
{
    echo "Uninstalling Morevna Studio..."
    # TODO: revert all operations done by install action
}

uninstall "$@"
