#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export MOREVNASTUDIO_DIR=`dirname "$SCRIPTPATH"`
MOREVNASTUDIO_DIR=`dirname "$MOREVNASTUDIO_DIR"`

uninstall()
{
    echo "Uninstalling Morevna Studio..."
    # TODO: revert all operations done by install action
    source ${MOREVNASTUDIO_DIR}/etc/morevna-studio.ini
    
    rm -rf "$HOME/.local/share/icons/morevnastudio-*"
    rm -rf "$HOME/.local/share/applications/morevnastudio-*"
    rm -rf "$HOME/.local/share/mime/packages/morevnastudio-*"
    
    update-desktop-database $HOME/.local/share/applications
}

uninstall "$@"
