#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export MOREVNASTUDIO_DIR=`dirname "$SCRIPTPATH"`
MOREVNASTUDIO_DIR=`dirname "$MOREVNASTUDIO_DIR"`

uninstall()
{
    echo "Uninstalling Morevna Studio..."
    source ${MOREVNASTUDIO_DIR}/etc/morevna-studio.ini
    
    rm -rf "$HOME/.local/share/icons/morevnastudio-*"
    rm -rf "$HOME/.local/share/applications/morevnastudio-*"
    rm -rf "$HOME/.local/share/mime/packages/morevnastudio-*"
    
    update-desktop-database $HOME/.local/share/applications
    
    if ( cat ~/.profile | grep "# morevna-studio/bin" >/dev/null ); then
        sed -i "/.*# morevna-studio\/bin.*/d"  ${HOME}/.profile
    fi
    if ( cat ~/.bash_profile | grep "# morevna-studio/bin" >/dev/null ); then
        sed -i "/.*# morevna-studio\/bin.*/d" $HOME/.bash_profile
    fi
    if ( cat ~/.xsessionrc | grep "# morevna-studio/bin" >/dev/null ); then
        sed -i "/.*# morevna-studio\/bin.*/d" ~/.xsessionrc
    fi
}

uninstall "$@"
