#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export MOREVNASTUDIO_DIR=`dirname "$SCRIPTPATH"`
MOREVNASTUDIO_DIR=`dirname "$MOREVNASTUDIO_DIR"`

install()
{
    echo "Installing Morevna Studio..."
    
    source ${MOREVNASTUDIO_DIR}/etc/morevna-studio.ini
    
    #[ -d $HOME/.local/morevna-studio/bin/ ] || mkdir -p $HOME/.local/morevna-studio/bin/
    # TODO: install scripts from "apps/" dir
    
    [ -d $HOME/.config/morevna-studio/ ] || mkdir -p $HOME/.config/morevna-studio/
    if [ ! -f $HOME/.config/morevna-studio/morevna-studio.ini ]; then
	#cp ${MOREVNASTUDIO_DIR}/etc/morevna-studio.ini $HOME/.config/morevna-studio/morevna-studio.ini

	# TODO: ask location for packages (allow to place on SSD partition)
	if false; then
	    [ -d /opt/morevna-studio/$USER ] || sudo mkdir -p /opt/morevna-studio/$USER
	    sudo chmod 700 /opt/morevna-studio/$USER
	    sudo chown $USER /opt/morevna-studio/$USER
	    echo "MOREVNASTUDIO_CACHEDIR=/opt/morevna-studio/$USER" >> $HOME/.config/morevna-studio/morevna-studio.ini
	fi
	
	#echo "MOREVNASTUDIO_LAUNCHER=\"${MOREVNASTUDIO_DIR}/bin/morevna-studio\"" >> $HOME/.config/morevna-studio/morevna-studio.ini
    fi
    
    [ -d "$HOME/.local/share/icons/" ] || mkdir -p "$HOME/.local/share/icons/"
    for FILE in `ls -1 "${MOREVNASTUDIO_DIR}/share/icons"`; do
	cp -f "${MOREVNASTUDIO_DIR}/share/icons/$FILE" "$HOME/.local/share/icons/"
    done
    
    [ -d "$HOME/.local/share/applications/" ] || mkdir -p "$HOME/.local/share/applications/"
    for FILE in `ls -1 "${MOREVNASTUDIO_DIR}/share/applications"`; do
	sed "s|Exec=|Exec=${MOREVNASTUDIO_DIR}/bin/|" \
	    "${MOREVNASTUDIO_DIR}/share/applications/$FILE" > "$HOME/.local/share/applications/$FILE"
    done
    
    [ -d "$HOME/.local/share/mime/packages/" ] || mkdir -p "$HOME/.local/share/mime/packages/"
    for FILE in `ls -1 "${MOREVNASTUDIO_DIR}/share/mime/packages"`; do
	cp -f "${MOREVNASTUDIO_DIR}/share/mime/packages/$FILE" "$HOME/.local/share/mime/packages/"
    done
    
    update-desktop-database $HOME/.local/share/applications
    
    #kbuildsycoca5 || kbuildsycoca4 --noincremental || true
    #update-mime-database $HOME/.local/share/mime/ || true
    
    echo "MOREVNASTUDIO_INSTALLED_VERSION=$MOREVNASTUDIO_VERSION" > $HOME/.config/morevna-studio/morevna-studio.version
    
    # Configure environment variables
    [ -f ${HOME}/.profile ] ||  ${HOME}/.profile
    if ( cat ~/.profile | grep "# morevna-studio/bin" >/dev/null ); then
	sed -i "/.*# morevna-studio\/bin.*/d"  ${HOME}/.profile
    fi
    echo "[ ! -z \${MOREVNASTUDIO_PATH_IS_SET} ] || export PATH=\"${MOREVNASTUDIO_DIR}/bin:\$PATH\" && export MOREVNASTUDIO_PATH_IS_SET=1 # morevna-studio/bin" >> ${HOME}/.profile
    [ -f ${HOME}/.bash_profile ] || touch ${HOME}/.bash_profile
    if ( cat ~/.bash_profile | grep "# morevna-studio/bin" >/dev/null ); then
	sed -i "/.*# morevna-studio\/bin.*/d" $HOME/.bash_profile
    fi
    echo "[ ! -z \${MOREVNASTUDIO_PATH_IS_SET} ] || export PATH=\"${MOREVNASTUDIO_DIR}/bin:\$PATH\" && export MOREVNASTUDIO_PATH_IS_SET=1 # morevna-studio/bin" >> ${HOME}/.bash_profile
    if ( cat ~/.xsessionrc | grep "# morevna-studio/bin" >/dev/null ); then
	sed -i "/.*# morevna-studio\/bin.*/d" ~/.xsessionrc
    fi
    echo "[ ! -z \${MOREVNASTUDIO_PATH_IS_SET} ] || export PATH=\"${MOREVNASTUDIO_DIR}/bin:\$PATH\" && export MOREVNASTUDIO_PATH_IS_SET=1 # morevna-studio/bin" >> ${HOME}/.xsessionrc

}

install "$@"
